apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-10-28T12:23:29Z"
  labels:
    app: kubernetes-bootcamp
    argocd.argoproj.io/instance: bootcamp
  name: kubernetes-bootcamp
  namespace: guestbook
spec:
  clusterIP: 10.224.238.244
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31339
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubernetes-bootcamp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
